# Generated by Django 5.1.2 on 2024-10-27 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='serie_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
